/**
 * TradeRetro color tokens.
 *
 * Raw values mirror the existing CSS variables in `src/index.css`.
 * Semantic tokens use CSS variables so components automatically respect the
 * active light/dark theme without changing visual output.
 */

export const rawColors = {
  dark: {
    bgRoot: '#0d0f0e',
    bgPanel: '#111413',
    bgInput: '#161918',
    bgHover: '#1c1f1e',
    bgElevated: '#232726',
    border: '#283030',
    borderSoft: '#1e2221',
    borderFocus: '#00c9a7',
    textPrimary: '#d4d9d7',
    textSecondary: '#6b7875',
    textMuted: '#3e4745',
    primary: '#00c9a7',
    primaryHover: '#00a888',
    green: '#4caf7d',
    red: '#e05252',
    blue: '#4a9eda',
    amber: '#e0a040',
    gold: '#f0c040',
    purple: '#9b72e0',
    orange: '#f07850',
  },
  light: {
    bgRoot: '#f6f7f6',
    bgPanel: '#ffffff',
    bgInput: '#eef1ef',
    bgHover: '#e4e8e5',
    bgElevated: '#dce2de',
    border: '#d1d9d4',
    borderSoft: '#e3e8e4',
    borderFocus: '#00a888',
    textPrimary: '#1a2420',
    textSecondary: '#4a5551',
    textMuted: '#7a8581',
    primary: '#00a888',
    primaryHover: '#008870',
    green: '#16a34a',
    red: '#dc2626',
    blue: '#2563eb',
    amber: '#d97706',
    gold: '#c89600',
    purple: '#7e56c4',
    orange: '#d96040',
  },
};

export const colors = {
  bgRoot: 'var(--bg-root)',
  bgPanel: 'var(--bg-panel)',
  bgInput: 'var(--bg-input)',
  bgHover: 'var(--bg-hover)',
  bgElevated: 'var(--bg-elevated)',
  border: 'var(--border)',
  borderSoft: 'var(--border-soft)',
  borderFocus: 'var(--border-focus)',
  textPrimary: 'var(--text-primary)',
  textSecondary: 'var(--text-secondary)',
  textMuted: 'var(--text-muted)',
  primary: 'var(--primary)',
  primaryHover: 'var(--primary-hover)',
  primaryBg: 'var(--primary-bg)',
  primaryHighlight: 'var(--primary-highlight)',
  green: 'var(--green)',
  greenBg: 'var(--green-bg)',
  greenHighlight: 'var(--green-highlight)',
  red: 'var(--red)',
  redBg: 'var(--red-bg)',
  redHighlight: 'var(--red-highlight)',
  blue: 'var(--blue)',
  blueBg: 'var(--blue-bg)',
  amber: 'var(--amber)',
  amberBg: 'var(--amber-bg)',
  amberHighlight: 'var(--amber-highlight)',
  gold: 'var(--gold)',
  purple: 'var(--purple)',
  orange: 'var(--orange)',
};

export const colorClasses = {
  surface: 'bg-[var(--bg-panel)] text-[var(--text-primary)]',
  elevated: 'bg-[var(--bg-elevated)] text-[var(--text-primary)]',
  input: 'bg-[var(--bg-input)] text-[var(--text-primary)]',
  hover: 'hover:bg-[var(--bg-hover)]',
  border: 'border-[var(--border)]',
  borderSoft: 'border-[var(--border-soft)]',
  primary: 'bg-[var(--primary)] text-[var(--bg-root)]',
  primaryHover: 'hover:bg-[var(--primary-hover)]',
  textPrimary: 'text-[var(--text-primary)]',
  textSecondary: 'text-[var(--text-secondary)]',
  textMuted: 'text-[var(--text-muted)]',
  positive: 'text-[var(--green)]',
  negative: 'text-[var(--red)]',
  warning: 'text-[var(--amber)]',
  info: 'text-[var(--blue)]',
};
