import { useMemo, useState } from 'react';
import { Terminal, BarChart3, LineChart, PieChart, List } from 'lucide-react';
import EquityChart from './EquityChart';
import TradeTable from './TradeTable';
import ErrorBoundary from './ErrorBoundary';
import ChartWidget from './ChartWidget';
import SummaryRibbon from './SummaryRibbon';
import RiskMetricsGrid from './RiskMetricsGrid';
import DrawdownChart from './DrawdownChart';
import MonthlyHeatmap from './MonthlyHeatmap';
import ReturnDistribution from './ReturnDistribution';
import TradeStats from './TradeStats';
import { analyze } from '../utils/performance';

function ExecutionWarning({ metadata }) {
  if (!metadata || metadata.executionEngine === 'python') return null;
  return (
    <div className="panel execution-warning">
      <div className="panel-title">Legacy Engine Fallback</div>
      <p>
        Results were generated by the legacy engine
        {metadata.fallbackReason ? ` because the Python engine reported: ${metadata.fallbackReason}` : ''}.
      </p>
    </div>
  );
}

function CostBreakdown({ costs }) {
  if (!costs) return null;
  const items = [
    { label: 'STT', value: costs.stt },
    { label: 'Brokerage', value: costs.brokerage },
    { label: 'Slippage', value: costs.slippage },
    { label: 'Exchange Fees', value: costs.exchangeFees },
    { label: 'GST', value: costs.gst },
    { label: 'Stamp Duty', value: costs.stampDuty },
  ];

  return (
    <div className="panel cost-breakdown-panel">
      <div className="panel-title-row">
        <span className="panel-title">Transaction Cost Breakdown</span>
        <span className="panel-sub">Indian regulatory model</span>
      </div>
      <div className="cost-breakdown-grid">
        {items.map((item) => (
          <div key={item.label} className="cost-item">
            <span className="cost-item-label">{item.label}</span>
            <span className="cost-item-value">
              &#8377;{item.value.toLocaleString('en-IN', { minimumFractionDigits: 2, maximumFractionDigits: 2 })}
            </span>
          </div>
        ))}
        <div className="cost-item cost-item-total">
          <span className="cost-item-label">Total Costs</span>
          <span className="cost-item-value">
            &#8377;{costs.totalCosts.toLocaleString('en-IN', { minimumFractionDigits: 2, maximumFractionDigits: 2 })}
          </span>
        </div>
        <div className="cost-item cost-item-total">
          <span className="cost-item-label">% of Capital</span>
          <span className="cost-item-value">{costs.costPctOfCapital.toFixed(2)}%</span>
        </div>
      </div>
    </div>
  );
}

function MonteCarloResults({ data }) {
  if (!data || !data.distribution) return null;
  const d = data.distribution;
  const barData = data.runs.map((r) => r.totalReturn).sort((a, b) => a - b);
  const bucketCount = 12;
  const min = barData[0];
  const max = barData[barData.length - 1];
  const bucketSize = (max - min) / bucketCount || 1;
  const buckets = Array.from({ length: bucketCount }, (_, i) => ({
    range: `${(min + i * bucketSize).toFixed(0)}%`,
    count: 0,
  }));
  barData.forEach((v) => {
    const idx = Math.min(Math.floor((v - min) / bucketSize), bucketCount - 1);
    buckets[idx].count++;
  });
  const maxCount = Math.max(...buckets.map((b) => b.count));

  return (
    <div className="results-container">
      <div className="panel monte-carlo-panel">
        <div className="panel-title-row">
          <span className="panel-title">Monte Carlo Distribution</span>
          <span className="panel-sub">{d.totalRuns} runs &middot; {data.executionTimeMs}ms</span>
        </div>

        <div className="mc-stats-grid">
          <div className="mc-stat">
            <span className="mc-stat-label">Mean Return</span>
            <span className={'mc-stat-value ' + (d.mean >= 0 ? 'positive' : 'negative')}>{d.mean.toFixed(2)}%</span>
          </div>
          <div className="mc-stat"><span className="mc-stat-label">Median</span><span className="mc-stat-value">{d.median.toFixed(2)}%</span></div>
          <div className="mc-stat"><span className="mc-stat-label">Std Dev</span><span className="mc-stat-value">{d.stdDev.toFixed(2)}%</span></div>
          <div className="mc-stat"><span className="mc-stat-label">Best Case</span><span className="mc-stat-value positive">{d.max.toFixed(2)}%</span></div>
          <div className="mc-stat"><span className="mc-stat-label">Worst Case</span><span className="mc-stat-value negative">{d.min.toFixed(2)}%</span></div>
          <div className="mc-stat"><span className="mc-stat-label">Win Rate</span><span className="mc-stat-value">{Math.round((d.positiveRuns / d.totalRuns) * 100)}%</span></div>
          <div className="mc-stat"><span className="mc-stat-label">5th Pctl</span><span className="mc-stat-value negative">{d.percentile5.toFixed(2)}%</span></div>
          <div className="mc-stat"><span className="mc-stat-label">95th Pctl</span><span className="mc-stat-value positive">{d.percentile95.toFixed(2)}%</span></div>
        </div>

        <div className="mc-histogram">
          <div className="mc-histogram-label">Return Distribution across {d.totalRuns} stochastic runs</div>
          <div className="mc-histogram-bars">
            {buckets.map((b, i) => (
              <div key={i} className="mc-bar-col">
                <div className="mc-bar" style={{ height: `${maxCount > 0 ? (b.count / maxCount) * 100 : 0}%` }} />
                <span className="mc-bar-label">{b.range}</span>
              </div>
            ))}
          </div>
        </div>
      </div>
    </div>
  );
}

export default function RightPane({
  mode, result, monteCarloResult, loading, error, applyCosts, theme,
  backtestTicker, strategyParams, backtestRange,
}) {
  const [activeTab, setActiveTab] = useState('performance');
  const isManual = mode === 'manual';
  const hasManualResults = isManual && !loading && result && result.metrics;
  const hasMonteCarloResults = isManual && !loading && monteCarloResult;
  const isIdle = !loading && !hasManualResults && !hasMonteCarloResults;

  const analytics = useMemo(
    () => (hasManualResults ? analyze(result, applyCosts) : null),
    [result, applyCosts, hasManualResults],
  );

  const metrics = hasManualResults
    ? (applyCosts ? result.metrics : { ...result.metrics, ...(result.grossMetrics || {}) })
    : null;

  return (
    <div className="right-pane">
      <div className="right-pane-header">
        <div className="right-pane-tabs">
          <button
            className={`right-pane-tab ${activeTab === 'performance' ? 'active' : ''}`}
            onClick={() => setActiveTab('performance')}
          >
            <BarChart3 size={14} />
            <span>Performance</span>
          </button>
          <button
            className={`right-pane-tab ${activeTab === 'risk' ? 'active' : ''}`}
            onClick={() => setActiveTab('risk')}
            disabled={!hasManualResults}
          >
            <PieChart size={14} />
            <span>Risk &amp; Returns</span>
          </button>
          <button
            className={`right-pane-tab ${activeTab === 'trades' ? 'active' : ''}`}
            onClick={() => setActiveTab('trades')}
            disabled={!hasManualResults}
          >
            <List size={14} />
            <span>Trades</span>
          </button>
          <button
            className={`right-pane-tab ${activeTab === 'chart' ? 'active' : ''}`}
            onClick={() => setActiveTab('chart')}
          >
            <LineChart size={14} />
            <span>Price Chart</span>
          </button>
        </div>
        {loading && <span className="right-pane-status pulse-dot">Running simulation&hellip;</span>}
      </div>

      {/* Price Chart tab */}
      {activeTab === 'chart' && (
        <div className="right-pane-scroll right-pane-chart">
          <ExecutionWarning metadata={result?.metadata || monteCarloResult?.metadata} />
          <ChartWidget
            theme={theme}
            ticker={backtestTicker}
            trades={result?.trades || []}
            backtestTicker={backtestTicker}
            strategyParams={strategyParams}
            dateRange={backtestRange}
          />
        </div>
      )}

      {activeTab !== 'chart' && (
        <div className="right-pane-scroll">
          {loading && (
            <div className="right-pane-loading">
              <div className="skeleton-ribbon" />
              <div className="skeleton-grid">
                {Array.from({ length: 8 }).map((_, i) => <div key={i} className="skeleton-card" />)}
              </div>
              <div className="skeleton-chart" />
            </div>
          )}

          {isIdle && (
            <div className="right-pane-idle">
              <Terminal size={40} />
              {error ? (
                <>
                  <p className="idle-title" style={{ color: 'var(--red)' }}>{error}</p>
                  <p className="idle-desc">Check your configuration and try again.</p>
                </>
              ) : (
                <>
                  <p className="idle-title">Awaiting Strategy Execution</p>
                  <p className="idle-desc">
                    Configure a strategy in the control panel and hit <strong>Run Backtest</strong>.
                  </p>
                </>
              )}
            </div>
          )}

          {/* Manual - Performance tab */}
          {hasManualResults && activeTab === 'performance' && (
            <div className="results-container">
              <ExecutionWarning metadata={result?.metadata} />

              <SummaryRibbon
                metrics={metrics}
                ticker={backtestTicker}
                strategy={strategyParams}
                range={backtestRange}
              />

              <RiskMetricsGrid metrics={metrics} analytics={analytics} applyCosts={applyCosts} />

              {metrics.totalTrades === 0 && (
                <div className="panel no-trade-warning">
                  <div className="panel-title">No Trades Executed</div>
                  <p>The strategy never triggered a buy signal during the selected period. Try adjusting parameters or widening the date range.</p>
                </div>
              )}

              <ErrorBoundary fallbackTitle="Equity Chart Failed" fallbackMessage="Equity curve data malformed.">
                {result.equityCurve && <EquityChart data={result.equityCurve} showCosts={applyCosts} />}
              </ErrorBoundary>

              {analytics?.drawdown && <DrawdownChart data={analytics.drawdown} />}

              {applyCosts && result.costBreakdown && <CostBreakdown costs={result.costBreakdown} />}
            </div>
          )}

          {/* Manual - Risk & Returns tab */}
          {hasManualResults && activeTab === 'risk' && analytics && (
            <div className="results-container">
              <SummaryRibbon
                metrics={metrics}
                ticker={backtestTicker}
                strategy={strategyParams}
                range={backtestRange}
              />
              <MonthlyHeatmap data={analytics.monthly} />
              <div className="risk-row">
                <ReturnDistribution data={analytics.histogram} />
              </div>
            </div>
          )}

          {/* Manual - Trades tab */}
          {hasManualResults && activeTab === 'trades' && (
            <div className="results-container">
              <SummaryRibbon
                metrics={metrics}
                ticker={backtestTicker}
                strategy={strategyParams}
                range={backtestRange}
              />
              {analytics?.trades && <TradeStats stats={analytics.trades} />}
              <ErrorBoundary fallbackTitle="Trade Table Failed" fallbackMessage="Trade data could not be rendered.">
                {result.trades && result.trades.length > 0 && <TradeTable trades={result.trades} applyCosts={applyCosts} />}
              </ErrorBoundary>
            </div>
          )}

          {hasMonteCarloResults && (
            <ErrorBoundary fallbackTitle="Monte Carlo Failed" fallbackMessage="Could not display distribution.">
              <MonteCarloResults data={monteCarloResult} />
            </ErrorBoundary>
          )}
        </div>
      )}
    </div>
  );
}
