import { useMemo, useState } from 'react';
import { Terminal, BarChart3, LineChart, PieChart, List, Grid3x3 } from 'lucide-react';
import EquityChart from './EquityChart';
import TradeTable from './TradeTable';
import ErrorBoundary from './ErrorBoundary';
import ChartWidget from './ChartWidget';
import SummaryRibbon from './SummaryRibbon';
import RiskMetricsGrid from './RiskMetricsGrid';
import DrawdownChart from './DrawdownChart';
import MonthlyHeatmap from './MonthlyHeatmap';
import ReturnDistribution from './ReturnDistribution';
import TradeStats from './TradeStats';
import ParameterSweep from './ParameterSweep';
import { analyze } from '../utils/performance';

function ExecutionWarning({ metadata }) {
  if (!metadata || metadata.executionEngine === 'python') return null;
  return (
    <div className="panel execution-warning">
      <div className="panel-title">Legacy Engine Fallback</div>
      <p>
        Results were generated by the legacy engine
        {metadata.fallbackReason ? ` because the Python engine reported: ${metadata.fallbackReason}` : ''}.
      </p>
    </div>
  );
}

function CostBreakdown({ costs }) {
  if (!costs) return null;
  const items = [
    { label: 'STT', value: costs.stt },
    { label: 'Brokerage', value: costs.brokerage },
    { label: 'Slippage', value: costs.slippage },
    { label: 'Exchange Fees', value: costs.exchangeFees },
    { label: 'GST', value: costs.gst },
    { label: 'Stamp Duty', value: costs.stampDuty },
  ];

  return (
    <div className="panel cost-breakdown-panel">
      <div className="panel-title-row">
        <span className="panel-title">Transaction Cost Breakdown</span>
        <span className="panel-sub">Indian regulatory model</span>
      </div>
      <div className="cost-breakdown-grid">
        {items.map((item) => (
          <div key={item.label} className="cost-item">
            <span className="cost-item-label">{item.label}</span>
            <span className="cost-item-value">
              &#8377;{item.value.toLocaleString('en-IN', { minimumFractionDigits: 2, maximumFractionDigits: 2 })}
            </span>
          </div>
        ))}
        <div className="cost-item cost-item-total">
          <span className="cost-item-label">Total Costs</span>
          <span className="cost-item-value">
            &#8377;{costs.totalCosts.toLocaleString('en-IN', { minimumFractionDigits: 2, maximumFractionDigits: 2 })}
          </span>
        </div>
        <div className="cost-item cost-item-total">
          <span className="cost-item-label">% of Capital</span>
          <span className="cost-item-value">{costs.costPctOfCapital.toFixed(2)}%</span>
        </div>
      </div>
    </div>
  );
}

export default function RightPane({
  mode, result, loading, error, applyCosts, theme,
  backtestTicker, strategyParams, backtestRange,
}) {
  const [activeTab, setActiveTab] = useState('performance');
  const isManual = mode === 'manual';
  const hasManualResults = isManual && !loading && result && result.metrics;
  const isIdle = !loading && !hasManualResults;

  const analytics = useMemo(
    () => (hasManualResults ? analyze(result, applyCosts) : null),
    [result, applyCosts, hasManualResults],
  );

  const metrics = hasManualResults
    ? (applyCosts ? result.metrics : { ...result.metrics, ...(result.grossMetrics || {}) })
    : null;

  return (
    <div className="right-pane">
      <div className="right-pane-header">
        <div className="right-pane-tabs">
          <button
            className={`right-pane-tab ${activeTab === 'performance' ? 'active' : ''}`}
            onClick={() => setActiveTab('performance')}
          >
            <BarChart3 size={14} />
            <span>Performance</span>
          </button>
          <button
            className={`right-pane-tab ${activeTab === 'risk' ? 'active' : ''}`}
            onClick={() => setActiveTab('risk')}
            disabled={!hasManualResults}
          >
            <PieChart size={14} />
            <span>Risk &amp; Returns</span>
          </button>
          <button
            className={`right-pane-tab ${activeTab === 'trades' ? 'active' : ''}`}
            onClick={() => setActiveTab('trades')}
            disabled={!hasManualResults}
          >
            <List size={14} />
            <span>Trades</span>
          </button>
          <button
            className={`right-pane-tab ${activeTab === 'chart' ? 'active' : ''}`}
            onClick={() => setActiveTab('chart')}
          >
            <LineChart size={14} />
            <span>Price Chart</span>
          </button>
          <button
            className={`right-pane-tab ${activeTab === 'sweep' ? 'active' : ''}`}
            onClick={() => setActiveTab('sweep')}
            disabled={!hasManualResults}
            title="Parameter sweep — vary 2 params, find robust sweet spot"
          >
            <Grid3x3 size={14} />
            <span>Sweep</span>
          </button>
        </div>
        {loading && <span className="right-pane-status pulse-dot">Running simulation&hellip;</span>}
      </div>

      {/* Price Chart tab */}
      {activeTab === 'chart' && (
        <div className="right-pane-scroll right-pane-chart">
          <ExecutionWarning metadata={result?.metadata} />
          <ChartWidget
            theme={theme}
            ticker={backtestTicker}
            trades={result?.trades || []}
            backtestTicker={backtestTicker}
            strategyParams={strategyParams}
            dateRange={backtestRange}
            equityCurve={result?.equityCurve || null}
            showCosts={applyCosts}
          />
        </div>
      )}

      {activeTab !== 'chart' && (
        <div className="right-pane-scroll">
          {loading && (
            <div className="right-pane-loading">
              <div className="skeleton-ribbon" />
              <div className="skeleton-grid">
                {Array.from({ length: 8 }).map((_, i) => <div key={i} className="skeleton-card" />)}
              </div>
              <div className="skeleton-chart" />
            </div>
          )}

          {isIdle && (
            <div className="right-pane-idle">
              <Terminal size={40} />
              {error ? (
                <>
                  <p className="idle-title" style={{ color: 'var(--red)' }}>{error}</p>
                  <p className="idle-desc">Check your configuration and try again.</p>
                </>
              ) : (
                <>
                  <p className="idle-title">Awaiting Strategy Execution</p>
                  <p className="idle-desc">
                    Configure a strategy in the control panel and hit <strong>Run Backtest</strong>.
                  </p>
                </>
              )}
            </div>
          )}

          {/* Manual - Performance tab */}
          {hasManualResults && activeTab === 'performance' && (
            <div className="results-container">
              <ExecutionWarning metadata={result?.metadata} />

              <SummaryRibbon
                metrics={metrics}
                ticker={backtestTicker}
                strategy={strategyParams}
                range={backtestRange}
              />

              <RiskMetricsGrid metrics={metrics} analytics={analytics} applyCosts={applyCosts} />

              {metrics.totalTrades === 0 && (
                <div className="panel no-trade-warning">
                  <div className="panel-title">No Trades Executed</div>
                  <p>The strategy never triggered a buy signal during the selected period. Try adjusting parameters or widening the date range.</p>
                </div>
              )}

              <ErrorBoundary fallbackTitle="Equity Chart Failed" fallbackMessage="Equity curve data malformed.">
                {result.equityCurve && <EquityChart data={result.equityCurve} showCosts={applyCosts} />}
              </ErrorBoundary>

              {analytics?.drawdown && <DrawdownChart data={analytics.drawdown} />}

              {applyCosts && result.costBreakdown && <CostBreakdown costs={result.costBreakdown} />}
            </div>
          )}

          {/* Manual - Risk & Returns tab */}
          {hasManualResults && activeTab === 'risk' && analytics && (
            <div className="results-container">
              <SummaryRibbon
                metrics={metrics}
                ticker={backtestTicker}
                strategy={strategyParams}
                range={backtestRange}
              />
              <MonthlyHeatmap data={analytics.monthly} />
              <div className="risk-row">
                <ReturnDistribution data={analytics.histogram} />
              </div>
            </div>
          )}

          {/* Manual - Trades tab */}
          {hasManualResults && activeTab === 'trades' && (
            <div className="results-container">
              <SummaryRibbon
                metrics={metrics}
                ticker={backtestTicker}
                strategy={strategyParams}
                range={backtestRange}
              />
              {analytics?.trades && <TradeStats stats={analytics.trades} />}
              <ErrorBoundary fallbackTitle="Trade Table Failed" fallbackMessage="Trade data could not be rendered.">
                {result.trades && result.trades.length > 0 && <TradeTable trades={result.trades} applyCosts={applyCosts} />}
              </ErrorBoundary>
            </div>
          )}

          {/* Manual - Parameter Sweep tab */}
          {hasManualResults && activeTab === 'sweep' && (
            <div className="results-container">
              <SummaryRibbon
                metrics={metrics}
                ticker={backtestTicker}
                strategy={strategyParams}
                range={backtestRange}
              />
              <ErrorBoundary fallbackTitle="Sweep Failed" fallbackMessage="Could not render parameter sweep.">
                <ParameterSweep
                  ticker={backtestTicker}
                  strategyType={strategyParams?.strategyType}
                  baseParams={{
                    initialCapital: metrics?.initialCapital || 100000,
                    // Strategy-specific defaults — used for the params NOT being swept
                    shortPeriod: strategyParams?.fastSma,
                    longPeriod: strategyParams?.slowSma,
                    rsiPeriod: strategyParams?.rsiPeriod,
                    oversold: strategyParams?.oversold,
                    overbought: strategyParams?.overbought,
                  }}
                  dateRange={backtestRange}
                />
              </ErrorBoundary>
            </div>
          )}
        </div>
      )}
    </div>
  );
}
